services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"

  parse-server:
    image: mashukealam/parseserver:v1
    container_name: parse-server
    ports:
      - "1337:1337"
      - "4040:4040"
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URI=mongodb://mongo:27017/
      - REDIS_CONNECTION_STRING=redis://redis:6379
  
  moralis-next-app:
    image: mashukealam/nextapp:v1
    container_name: moralis-next-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - parse-server
      - sanity
  sanity:
    image: mashukealam/sanity:v1
    container_name: sanity
    ports:
      - "3333:3333"
    networks:
      - app-networks

volumes:
  mongo-data:

networks:
  app-networks:
    driver: bridge
