name: Deploy to server when repository gets updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 62.72.7.168
          username: root
          key: ${{ secrets.SSH_PRIV }}
          port: 22
          script: |
            cd /root/
            echo "github was here" >> ghost.txt