name: Deploy to server when repository gets updated
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIV }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Ghost from GitHub was here at $(date '+%B %d, %Y %I:%M:%S %p')" >> /root/ghost.log
            cd /root/app/NomadsConnect
            docker compose down
            echo "Ghost tried to nuke the Docker instance at $(date '+%B %d, %Y %I:%M:%S %p')" >> /root/ghost.log
            git checkout main
            git pull 
            docker compose up --build -d


